// export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const SERVICES_UPLOAD_REQUEST = "SERVICES_UPLOAD_REQUEST"
export const SERVICES_UPLOAD_FAILURE = "SERVICES_UPLOAD_FAILURE"
export const SERVICES_UPLOAD_SUCCESS = "SERVICES_UPLOAD_SUCCESS"

export const SERVICE_DETAILS_UPLOAD_REQUEST = "SERVICE_DETAILS_UPLOAD_REQUEST"
export const SERVICE_DETAILS_UPLOAD_FAILURE = "SERVICE_DETAILS_UPLOAD_FAILURE"
export const SERVICE_DETAILS_UPLOAD_SUCCESS = "SERVICE_DETAILS_UPLOAD_SUCCESS"
